FROM jenkins/jenkins:lts
# Copies [first file, the local one] to [second path/file this place in the container]
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY jenkins.yaml /var/jenkins_conf/jenkins.yaml
COPY jenkins_jobs.ini /etc/jenkins_jobs/jenkins_jobs.ini
COPY fsjob.xml /jobs/fsjob.xml

ENV JAVA_OPTS "-Djenkins.install.runSetupWizard=false"
ENV JENKINS_USER admin
ENV JENKINS_PASS admin
ENV DOCKERVERSION=18.03.1-ce
ENV CASC_JENKINS_CONFIG /var/jenkins_conf

# Run from Root
USER root

# Update linux
RUN apt-get update
# Install maven
RUN apt-get install -y maven 
# Download Docker, unzip it (I guess), then rm the zipped version
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz
RUN tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker
RUN rm docker-${DOCKERVERSION}.tgz
# Download kubectl, change the permission, and then move it to the right dir so we can use it
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

# Stop running from Root
USER jenkins

# Install Plugins
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt